// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhxcwxnlvsdqwjuqekpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoeGN3eG5sdnNkcXdqdXFla3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTgyODEsImV4cCI6MjA2NzEzNDI4MX0.8OJ2Sy_1cJJwc9wG92QjbioeqxI8vYriHwNEQHqCdlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});